package dev.perfectbogus.design.patterns.behavioral.template.report;

// Task 5 — Uses the hook method to prepend an audit line to every report.
// Reuses the same CSV data/format/header/footer logic as CsvReportGenerator.
public class AuditableReportGenerator extends ReportGenerator {

    // TODO: private fields for title and auditUser
    private final String title;
    private final String auditUser;

    // TODO: constructor accepting String title and String auditUser
    public AuditableReportGenerator(String title, String auditUser) {
        this.title = title;
        this.auditUser = auditUser;
    }

    // TODO: same fetchData as CsvReportGenerator
    @Override
    public String fetchData() {
        return "id,name,amount\n1,Alice,200\n2,Bob,150";
    }

    // TODO: same formatData as CsvReportGenerator
    @Override
    public String formatData(String data) {
        return data;
    }

    // TODO: same buildHeader as CsvReportGenerator
    @Override
    public String buildHeader() {
        return "=== " + title + " ===";
    }

    // TODO: same buildFooter as CsvReportGenerator
    @Override
    public String buildFooter() {
        return "--- end of report ---";
    }
    // TODO: override onBeforeGenerate() →
    //       returns "[AUDIT] Report generated by: " + auditUser
    @Override
    public String onBeforeGenerate() {
        return "[AUDIT] Report generated by: " + auditUser;
    }
}
