package dev.perfectbogus.design.patterns.behavioral.template.report;

// Task 5 — Uses the hook method to prepend an audit line to every report.
// Reuses the same CSV data/format/header/footer logic as CsvReportGenerator.
public class AuditableReportGenerator extends CsvReportGenerator {

    // TODO: private fields for title and auditUser
    private final String auditUser;

    // TODO: constructor accepting String title and String auditUser
    public AuditableReportGenerator(String title, String auditUser) {
        super(title);
        this.auditUser = auditUser;
    }

    // TODO: override onBeforeGenerate() →
    //       returns "[AUDIT] Report generated by: " + auditUser
    @Override
    public String onBeforeGenerate() {
        return "[AUDIT] Report generated by: " + auditUser;
    }
}
