package dev.perfectbogus.design.patterns.behavioral.template.report;

// Task 3 — HTML concrete implementation of ReportGenerator.
// formatData wraps each comma-separated entry in <li> tags inside a <ul>.
public class HtmlReportGenerator extends ReportGenerator {

    // TODO: private field for title
    private final String title;

    // TODO: constructor accepting String title
    public HtmlReportGenerator(String title) {
        this.title = title;
    }

    // TODO: fetchData() → "Alice:200,Bob:150"
    @Override
    public String fetchData() {
        return "Alice:200,Bob:150";
    }

    // TODO: formatData(String data):
    //       split data by "," → wrap each entry in <li>...</li>
    //       wrap all <li> elements in <ul>...</ul>
    //       Example output: "<ul><li>Alice:200</li><li>Bob:150</li></ul>"
    @Override
    public String formatData(String data) {
        String[] split = data.split(",");
        StringBuilder sb = new StringBuilder();
        sb.append("<ul>");
        for (String s : split) {
            sb.append("<li>").append(s).append("</li>");
        }
        sb.append("</ul>");
        return sb.toString();
    }

    // TODO: buildHeader() → "<h1>" + title + "</h1>"
    @Override
    public String buildHeader() {
        return "<h1>" + title + "</h1>";
    }


    // TODO: buildFooter() → "<footer>Generated by ReportGenerator</footer>"
    @Override
    public String buildFooter() {
        return "<footer>Generated by ReportGenerator</footer>";
    }
}
