package dev.perfectbogus.design.patterns.behavioral.template.report;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class ReportGeneratorTest {

    // -------------------------------------------------------------------------
    // Task 1 + 2 — ReportGenerator skeleton + CsvReportGenerator
    // -------------------------------------------------------------------------
    @Nested
    @DisplayName("Task 1 & 2 - CsvReportGenerator")
    class Task1And2 {

        @Test
        @DisplayName("generate() should call steps in correct order")
        void shouldCallStepsInOrder() {
            var generator = new CsvReportGenerator("Monthly Report");
            var report    = generator.generate();
            var parts     = report.split("\n");
            assertEquals("=== Monthly Report ===",  parts[0]); // header first
            assertTrue(parts[2].contains("Alice"));            // data second
            assertEquals("--- end of report ---",   parts[parts.length - 1]); // footer last
        }

        @Test
        @DisplayName("generate() should produce the correct full report")
        void shouldProduceCorrectReport() {
            var generator = new CsvReportGenerator("Sales");
            var expected  = "=== Sales ===\n" +
                            "id,name,amount\n1,Alice,200\n2,Bob,150\n" +
                            "--- end of report ---";
            assertEquals(expected, generator.generate());
        }

        @Test
        @DisplayName("fetchData, formatData, buildHeader, buildFooter should be abstract")
        void abstractMethodsShouldBeAbstract() throws Exception {
            assertTrue(java.lang.reflect.Modifier.isAbstract(
                    ReportGenerator.class.getDeclaredMethod("fetchData").getModifiers()));
            assertTrue(java.lang.reflect.Modifier.isAbstract(
                    ReportGenerator.class.getDeclaredMethod("formatData", String.class).getModifiers()));
            assertTrue(java.lang.reflect.Modifier.isAbstract(
                    ReportGenerator.class.getDeclaredMethod("buildHeader").getModifiers()));
            assertTrue(java.lang.reflect.Modifier.isAbstract(
                    ReportGenerator.class.getDeclaredMethod("buildFooter").getModifiers()));
        }
    }

    // -------------------------------------------------------------------------
    // Task 3 — HtmlReportGenerator
    // -------------------------------------------------------------------------
    @Nested
    @DisplayName("Task 3 - HtmlReportGenerator")
    class Task3 {

        @Test
        @DisplayName("generate() should produce valid HTML structure")
        void shouldProduceHtmlStructure() {
            var generator = new HtmlReportGenerator("Product Report");
            var report    = generator.generate();
            System.out.println(report);

            assertTrue(report.contains("<h1>Product Report</h1>"));
            assertTrue(report.contains("<ul>"));
            assertTrue(report.contains("<li>Alice:200</li>"));
            assertTrue(report.contains("<li>Bob:150</li>"));
            assertTrue(report.contains("</ul>"));
            assertTrue(report.contains("<footer>Generated by ReportGenerator</footer>"));
        }

        @Test
        @DisplayName("generate() should produce the correct full HTML report")
        void shouldProduceCorrectFullReport() {
            var generator = new HtmlReportGenerator("Products");
            var expected  =
                    "<h1>Products</h1>\n" +
                            "<ul><li>Alice:200</li><li>Bob:150</li></ul>\n" +
                            "<footer>Generated by ReportGenerator</footer>";
            assertEquals(expected, generator.generate());
        }

        @Test
        @DisplayName("Header should come before data, footer after")
        void shouldRespectOrder() {
            var report = new HtmlReportGenerator("Test").generate();
            int headerIdx = report.indexOf("<h1>");
            int dataIdx   = report.indexOf("<ul>");
            int footerIdx = report.indexOf("<footer>");

            assertTrue(headerIdx < dataIdx);
            assertTrue(dataIdx   < footerIdx);
        }
    }

    // -------------------------------------------------------------------------
    // Task 4 — Hook method onBeforeGenerate
    // -------------------------------------------------------------------------
    @Nested
    @DisplayName("Task 4 - Hook method onBeforeGenerate")
    class Task4 {

        @Test
        @DisplayName("Default hook should return empty string and not affect output")
        void defaultHookShouldNotAffectOutput() {
            var generator    = new CsvReportGenerator("Sales");
            var withoutHook  =
                    "=== Sales ===\n" +
                            "id,name,amount\n1,Alice,200\n2,Bob,150\n" +
                            "--- end of report ---";
            assertEquals(withoutHook, generator.generate());
        }

        @Test
        @DisplayName("onBeforeGenerate should be non-abstract with empty string default")
        void hookShouldHaveDefaultEmptyImpl() throws Exception {
            var method = ReportGenerator.class.getDeclaredMethod("onBeforeGenerate");
            assertFalse(java.lang.reflect.Modifier.isAbstract(method.getModifiers()),
                    "onBeforeGenerate must NOT be abstract — it has a default implementation");
        }
    }

    // -------------------------------------------------------------------------
    // Task 5 — AuditableReportGenerator
    // -------------------------------------------------------------------------
    @Nested
    @DisplayName("Task 5 - AuditableReportGenerator")
    class Task5 {

        @Test
        @DisplayName("generate() should prepend audit line at the very top")
        void shouldPrependAuditLine() {
            var generator = new AuditableReportGenerator("Audit Report", "admin");
            var report    = generator.generate();
            var lines     = report.split("\n");

            assertEquals("[AUDIT] Report generated by: admin", lines[0]);
        }

        @Test
        @DisplayName("generate() should produce correct full auditable report")
        void shouldProduceCorrectAuditableReport() {
            var generator = new AuditableReportGenerator("Sales", "alice");
            var expected  =
                    "[AUDIT] Report generated by: alice\n" +
                            "=== Sales ===\n" +
                            "id,name,amount\n1,Alice,200\n2,Bob,150\n" +
                            "--- end of report ---";
            assertEquals(expected, generator.generate());
        }

        @Test
        @DisplayName("Audit line should appear before the header")
        void auditLineShouldBeBeforeHeader() {
            var report    = new AuditableReportGenerator("R", "bob").generate();
            int auditIdx  = report.indexOf("[AUDIT]");
            int headerIdx = report.indexOf("===");
            assertTrue(auditIdx < headerIdx);
        }
    }

    // -------------------------------------------------------------------------
    // Task 6 — ValidatedReportGenerator + NonEmptyReportGenerator
    // -------------------------------------------------------------------------
    @Nested
    @DisplayName("Task 6 - ValidatedReportGenerator + NonEmptyReportGenerator")
    class Task6 {

        @Test
        @DisplayName("Should generate report normally when data is valid")
        void shouldGenerateWhenValid() {
            var generator = new NonEmptyReportGenerator("Report", "id,name\n1,Alice");
            var report    = generator.generate();
            assertTrue(report.contains("Alice"));
            assertTrue(report.contains("=== Report ==="));
            assertTrue(report.contains("--- end of report ---"));
        }

        @Test
        @DisplayName("Should return error message when data is blank")
        void shouldReturnErrorWhenDataIsBlank() {
            var generator = new NonEmptyReportGenerator("Report", "");
            assertEquals("[ERROR] Report data failed validation", generator.generate());
        }

        @Test
        @DisplayName("Should return error message when data is whitespace only")
        void shouldReturnErrorWhenDataIsWhitespace() {
            var generator = new NonEmptyReportGenerator("Report", "   ");
            assertEquals("[ERROR] Report data failed validation", generator.generate());
        }

        @Test
        @DisplayName("Should NOT call buildHeader or buildFooter when validation fails")
        void shouldNotCallOtherStepsWhenInvalid() {
            var generator = new NonEmptyReportGenerator("Report", "");
            var result    = generator.generate();
            assertFalse(result.contains("==="),
                    "Header must not appear when validation fails");
            assertFalse(result.contains("end of report"),
                    "Footer must not appear when validation fails");
        }

        @Test
        @DisplayName("ValidatedReportGenerator should be abstract")
        void validatedGeneratorShouldBeAbstract() {
            assertTrue(java.lang.reflect.Modifier.isAbstract(
                    ValidatedReportGenerator.class.getModifiers()));
        }
    }
}